### ISSUE TITLE
figlet dependencies

### ISSUE THREAD

**Issue by fdncred** [nushell-prophet/dotnu#5]
You need figlet and the fonts from https://github.com/PhMajerus/FIGfonts too. cool stuff though!

**Comment by maxim-uvarov** [comment]
Yeah, thanks:) i should include this note into `demo.nu`

But for dotnu itself they are not needed

**Comment by maxim-uvarov** [comment]
Dotnu is pure nushell!

**Comment by maxim-uvarov** [comment]
thanks, Darren!
